CREATE TABLE users (
	id INT PRIMARY KEY,
	username VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
	id INT PRIMARY KEY,
	content VARCHAR NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE direct_messages (
	id INT PRIMARY KEY,
	user_id INT NOT NULL,
	peer_id INT NOT NULL,
	message_id INT NOT NULL,
	direction VARCHAR NOT NULL,
	seen_at TIMESTAMPTZ NULL
);